[package]
name = "synthetic-data-openai-compatible"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
generation-core.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
axum.workspace = true
tokio.workspace = true

[lints]
workspace = true
