import { mkdirSync, writeFileSync, readFileSync, existsSync, renameSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import type { BrowserWindow } from "electron";
import type { ProjectRegistry } from "./project-registry.js";

interface Harness { registry: ProjectRegistry; chooseFolder(path?: string): void; restart: boolean }
/** Actual Electron UI + persistence checks. All local projects are deterministic temporary fixtures. */
export async function runSmokeChecks(window: BrowserWindow, output: string, harness: Harness): Promise<void> {
  mkdirSync(output, { recursive: true });
  const web = window.webContents;
  const evaluate = (code: string) => web.executeJavaScript(code, true);
  const until = async (expression: string) => evaluate("new Promise((resolve,reject)=>{let n=0;const poll=()=>{if(" + expression + ")resolve(true);else if(n++>250)reject(new Error('Timed out: '+ " + JSON.stringify(expression) + "));else setTimeout(poll,20)};poll()})");
  const check = async (name: string, expression: string) => {
    if (!await evaluate(expression)) {
      console.log(await evaluate("JSON.stringify({width:innerWidth,root:document.documentElement.scrollWidth,page:{client:document.getElementById('page').clientWidth,scroll:document.getElementById('page').scrollWidth},overflow:[...document.querySelectorAll('#page > *, .page-content > *, .workspace-header')].map(e=>({class:e.className,right:e.getBoundingClientRect().right,scroll:e.scrollWidth,client:e.clientWidth}))})"));
      throw new Error("Renderer check failed: " + name);
    }
    console.log("PASS " + name);
  };
  const click = async (selector: string) => evaluate("document.querySelector(" + JSON.stringify(selector) + ").click()");
  const textButton = async (text: string) => evaluate("[...document.querySelectorAll('#page button, dialog[open] button')].find(b=>b.textContent === " + JSON.stringify(text) + ").click()");
  const nav = async (page: string) => click('[data-page="' + page + '"]');
  const type = async (id: string, value: string) => evaluate("document.getElementById(" + JSON.stringify(id) + ").value=" + JSON.stringify(value) + ";document.getElementById(" + JSON.stringify(id) + ").dispatchEvent(new Event('input',{bubbles:true}));");
  const select = async (id: string, value: string) => evaluate("document.getElementById(" + JSON.stringify(id) + ").value=" + JSON.stringify(value) + ";document.getElementById(" + JSON.stringify(id) + ").dispatchEvent(new Event('change',{bubbles:true}));");
  const loaded = async () => until("!document.getElementById('source-state').textContent.includes('Reading') && document.querySelector('#page h1')");
  const paint = async () => { await evaluate("new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)))"); };
  const screenshot = async (name: string, width = 1440, height = 960) => { window.setContentSize(width, height); await paint(); writeFileSync(join(output, name + ".png"), (await web.capturePage()).toPNG()); };
  await until("document.querySelector('#page h1')");

  if (harness.restart) {
    await loaded();
    await check("second Electron process restores project collection and selection", "document.querySelectorAll('[data-project-id]').length === 2 && document.getElementById('breadcrumb').textContent.includes('Support encoder')");
    await check("second process reads its own candidate and metric contract", "document.querySelectorAll('[data-candidate-id]').length === 1 && document.querySelector('.candidate-table thead').textContent.includes('Macro F1')");
    await check("theme and keyboard-resized sidebar survive restart", "document.documentElement.dataset.theme === 'light' && document.getElementById('sidebar-resizer').getAttribute('aria-valuenow') === '248'");
    await screenshot("projects-restored");
    return;
  }

  await check("first launch has no hard-coded project", "document.querySelector('.welcome-page') && document.querySelectorAll('[data-project-id]').length === 0 && !document.getElementById('page').textContent.includes('Nomos')");
  await screenshot("welcome-dark");
  await click("#theme-toggle"); await screenshot("welcome-light"); await click("#theme-toggle");
  await click("#open-recorded-example"); await until("document.querySelectorAll('[data-candidate-id]').length === 15");
  const exampleId = harness.registry.read().selectedId!;
  await check("example opens only after an explicit request", "document.getElementById('source-state').textContent.includes('Recorded example')");
  await screenshot("models-dark");
  await click(".candidate-link");
  await check("repair candidate shows six failed checks", "document.querySelectorAll('.evidence-table tbody tr').length === 6");
  await screenshot("candidate-results");
  await click("#failed-only");
  await check("all 26 recorded checks can be inspected", "document.querySelectorAll('.evidence-table tbody tr').length === 26");
  await click("#tab-training");
  await check("training configuration retains exact input counts", "document.getElementById('detail-panel').textContent.includes('6992')");
  await screenshot("candidate-training");
  await evaluate("document.getElementById('tab-training').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}))");
  await check("keyboard tabs change panel and move focus", "document.activeElement.id === 'tab-artifact' && document.getElementById('detail-panel').textContent.includes('36289478c89d50b3')");
  await nav("models");
  await evaluate("document.getElementById('candidate-search').focus()");
  await type("candidate-search", "repair");
  await check("search filters without losing focus", "document.querySelectorAll('[data-candidate-id]').length === 1 && document.activeElement.id === 'candidate-search'");
  await click(".candidate-link"); await click("#navigate-back");
  await check("back retains model search", "document.getElementById('candidate-search').value === 'repair' && document.querySelectorAll('[data-candidate-id]').length === 1");
  await type("candidate-search", "no-matching-candidate");
  await check("empty search has recovery", "document.querySelector('.empty-state').textContent.includes('Reset filters')");
  await click(".empty-state button");
  await select("status-filter", "passed");
  await check("recorded result filter is functional", "document.querySelectorAll('[data-candidate-id]').length === 2");
  await select("status-filter", "all");
  await select("suite-0", "1");
  await check("benchmark selection changes the visible baseline", "document.querySelector('.baseline-table-row').textContent.includes('0.966499')");
  await select("suite-0", "0");
  for (let i = 0; i < 3; i++) await evaluate("document.querySelectorAll('[data-candidate-id] input')[" + i + "].click()");
  await evaluate("document.querySelectorAll('.comparison-group')[1].querySelector('[data-candidate-id] input').click()");
  await check("different evaluation setups cannot be mixed", "document.querySelectorAll('[data-candidate-id] input:checked').length === 3 && document.getElementById('toast').textContent.includes('same evaluation setup')");
  await click("#compare-selected");
  await check("comparison shows baseline and all three selected candidates", "document.querySelectorAll('.compare-matrix').length === 2 && document.querySelector('.comparison-matrix thead tr').children.length === 5");
  await screenshot("compare-dark");
  await nav("runs");
  await check("nine original run records remain available", "document.querySelectorAll('.run-list-item').length === 9");
  await screenshot("runs-dark");
  await click(".run-list-item"); await click("#tab-activity");
  await check("run activity comes from journal events", "document.querySelectorAll('.activity-list li').length > 4");
  await click("#tab-record");
  await check("immutable optimization identity remains inspectable", "document.getElementById('detail-panel').textContent.includes('2317e08b-5848-4773-9a9e-42499ee09815')");
  await nav("runs"); await evaluate("[...document.querySelectorAll('.run-list-item')].at(-1).click()"); await click(".run-candidate button");
  await check("failed historical attempt never borrows a recovered model's results", "document.querySelector('.result-banner').textContent.includes('Execution failed') && document.querySelectorAll('.evidence-table tbody tr').length === 0");
  await nav("benchmarks"); await check("benchmark setups remain separate", "document.querySelectorAll('.benchmark-section').length > 1");
  await nav("models"); await click(".baseline-action button");
  await check("baseline artifact identity is available", "document.getElementById('page').textContent.includes('0c0f6a80a2e34c0')");
  await nav("models"); await click(".candidate-table .metric-heading");
  await check("metric explanation opens accessibly", "document.querySelector('dialog[open] h2').textContent === 'Ranking score'");
  await evaluate("document.querySelector('dialog[open]').close()");
  await textButton("Clear selection");
  await click("#theme-toggle"); await screenshot("models-light"); await click("#theme-toggle");
  for (const [width, height] of [[1280, 820], [1024, 768], [760, 800], [390, 844]] as const) {
    await screenshot("models-" + width, width, height);
    await check("no page overflow at " + width, "document.getElementById('page').scrollWidth <= document.getElementById('page').clientWidth + 1 && document.documentElement.scrollWidth <= window.innerWidth");
    if (width >= 1024) await check("a complete candidate is visible at " + width, "document.querySelector('[data-candidate-id]').getBoundingClientRect().bottom < window.innerHeight");
  }
  await click("#sidebar-menu");
  await check("mobile sidebar can be opened", "document.getElementById('sidebar-menu').getAttribute('aria-expanded') === 'true'");
  await nav("models");
  await check("mobile navigation closes sidebar and updates accessibility state", "document.getElementById('sidebar-menu').getAttribute('aria-expanded') === 'false'");
  window.setContentSize(1440, 960); await paint();

  // All folder tests use real metadata IPC and temporary synthetic SQLite records.
  const { experimentFixture, writeExperimentDatabase } = await import(pathToFileURL(join(output, "..", "tests", "fixtures", "experiment.mjs")).href);
  const root = join(harness.registry.file, "..", "fixture-projects");
  mkdirSync(root, { recursive: true });
  const draft = join(root, "draft-encoder"), support = join(root, "support-encoder"), semantic = join(root, "semantic-encoder");
  for (const folder of [draft, support, semantic]) mkdirSync(folder);
  writeExperimentDatabase(join(support, "experiment.db"), experimentFixture("support"));
  const f = experimentFixture("semantic");
  f.project.baseline_model.fingerprint = "sha256:" + "a".repeat(64);
  f.protocol.metric_contract.primary_metric = "mean_squared_error";
  f.protocol.metric_contract.definitions = [{ key: "mean_squared_error", direction: "lower_is_better" }, { key: "spearman_correlation", direction: "higher_is_better" }];
  f.protocol.baseline_development_report.metrics = { mean_squared_error: 0.12, spearman_correlation: 0.7 };
  f.events[3].event.report.metrics = { mean_squared_error: 0.10, spearman_correlation: 0.75 };
  f.events[3].event.assessment.gates = [{ key: "mean_squared_error", baseline: 0.12, candidate: 0.10, direction_adjusted_improvement: 0.02, condition: { kind: "minimum_improvement", value: 0.03 }, passed: false }];
  writeExperimentDatabase(join(semantic, "semantic.sqlite3"), f);
  const before = readFileSync(join(support, "experiment.db"));
  const add = async (folder: string) => { harness.chooseFolder(folder); await click("#add-project"); await until("document.getElementById('breadcrumb').textContent.includes(" + JSON.stringify(folder.split(/[\\/]/).at(-1)) + ")"); await loaded(); };
  const open = async (id: string) => { await click('[data-project-id="' + id + '"]'); await loaded(); };
  await add(draft);
  const draftId = harness.registry.read().selectedId!;
  await check("an empty project is a valid first-use state", "document.querySelector('.empty-baseline') && document.getElementById('page').textContent.includes('No baseline recorded yet')");
  await screenshot("empty-project");
  await nav("runs"); await check("empty project run page has its own purpose", "document.querySelector('#page h1').textContent === 'Runs' && document.getElementById('page').textContent.includes('No runs recorded yet')");
  await nav("benchmarks"); await check("empty project benchmark page has its own purpose", "document.querySelector('#page h1').textContent === 'Benchmarks' && document.getElementById('page').textContent.includes('No benchmark results recorded yet')");
  await add(support);
  const supportId = harness.registry.read().selectedId!;
  await check("generic project uses its own model and metrics", "document.querySelector('.baseline-name h2').textContent === 'support-encoder' && document.querySelector('.candidate-table thead').textContent.includes('Macro F1') && !document.querySelector('.candidate-table').textContent.includes('MRR')");
  await screenshot("classification-project");
  await nav("benchmarks"); await check("generic benchmark detail uses the project's primary metric", "document.querySelector('.benchmark-row').textContent.includes('macro f1') && !document.querySelector('.benchmark-row').textContent.includes('MRR')");
  await nav("models"); await click(".baseline-action button");
  await check("generic baseline details use the same metric contract", "document.querySelector('.baseline-evaluation thead').textContent.includes('Macro F1') && document.querySelector('.baseline-evaluation').textContent.includes('75.00%')");
  await nav("models");
  await click("[data-candidate-id] input"); await type("candidate-search", "fine");
  await add(semantic);
  const semanticId = harness.registry.read().selectedId!;
  await check("switching isolates search and selection", "document.getElementById('candidate-search').value === '' && document.querySelectorAll('input:checked').length === 0 && document.querySelectorAll('[data-candidate-id]').length === 1");
  await check("lower-is-better metric direction comes from the contract", "document.querySelector('.candidate-table .metric-heading').textContent.includes('↓') && document.querySelector('[data-candidate-id] .score-stack small').classList.contains('success')");
  await screenshot("similarity-project");
  await open(supportId);
  await check("returning restores this project's own comparison context", "document.getElementById('candidate-search').value === 'fine' && document.querySelectorAll('[data-candidate-id] input:checked').length === 1");
  await nav("project"); await textButton("Rename project"); await type("project-name-input", "Support encoder"); await textButton("Save name");
  await until("!document.querySelector('#project-dialog[open]') && document.getElementById('breadcrumb').textContent.includes('Support encoder')");
  await check("renaming preserves project identity and folder", "document.querySelector('[data-project-id=" + JSON.stringify(supportId) + "]').textContent.includes('Support encoder')");
  await open(draftId);
  writeExperimentDatabase(join(draft, "prepared.db"), experimentFixture("draft"), false);
  await click("#reload-evidence"); await loaded();
  await check("baseline-only project has a useful no-candidates state", "document.querySelector('.baseline-name') && document.getElementById('page').textContent.includes('No candidates recorded yet') && document.querySelectorAll('[data-candidate-id]').length === 0");
  await screenshot("baseline-only");
  await open(semanticId);
  const moved = join(root, "semantic-moved"); renameSync(semantic, moved);
  await click("#reload-evidence"); await loaded();
  await check("missing folder never displays another project's scores", "document.querySelector('.empty-state').textContent.includes('no longer available') && document.querySelectorAll('[data-candidate-id]').length === 0");
  await screenshot("missing-folder");
  harness.chooseFolder(moved); await textButton("Locate folder"); await until("document.querySelectorAll('[data-candidate-id]').length === 1"); await loaded();
  await check("reconnection keeps identity and restores exact model", "document.querySelectorAll('[data-candidate-id]').length === 1 && document.querySelector('.baseline-name').textContent.includes('semantic-encoder')");
  const reconnected = harness.registry.get(semanticId).source;
  if (reconnected.kind !== "folder" || reconnected.path !== moved) throw new Error("Reconnection did not persist");
  await open(draftId); await nav("project"); await textButton("Remove project entry…"); await textButton("Remove entry");
  await until("!document.querySelector('#project-dialog[open]')"); await loaded();
  if (!existsSync(join(draft, "prepared.db"))) throw new Error("Removing a project deleted its files");
  await check("removal only forgets the chosen project entry", "document.querySelectorAll('[data-project-id]').length === 3");
  await open(exampleId); await nav("project"); await textButton("Remove project entry…"); await textButton("Remove entry");
  await until("!document.querySelector('#project-dialog[open]')"); await loaded();
  await open(supportId); await type("candidate-search", ""); await textButton("Clear selection");
  if (!before.equals(readFileSync(join(support, "experiment.db")))) throw new Error("A UI operation modified experiment evidence");
  console.log("PASS all project UI operations preserve experiment database bytes");
  await screenshot("project-folders");
  await click("#theme-toggle");
  await evaluate("document.getElementById('sidebar-resizer').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}))");
  await screenshot("project-folders-light");
  console.log("Encoder Gym renderer acceptance checks passed.");
}
