[package]
name = "encoder-experiment-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
encoder-experiment-core.workspace = true
serde_json.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
