[package]
name = "dataset-quality-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
artifact-core.workspace = true
chrono.workspace = true
dataset-core.workspace = true
generation-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
