[alias]
check-all = "check --workspace --all-targets --all-features"
fmt-check = "fmt --all -- --check"
lint = "clippy --workspace --all-targets --all-features -- -D warnings"
test-all = "test --workspace --all-targets --all-features"
